package dev.gwaboard.shared.crypto

import javax.crypto.Cipher
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * AES-256-GCM encrypt/decrypt operations for IPC payload protection.
 *
 * Each encryption generates a fresh 12-byte IV (never reused).
 * The GCM authentication tag (128-bit) is appended to the ciphertext
 * by the Android Cipher implementation.
 *
 * Usage:
 * ```
 * val cipher = SessionCipher()
 * val encrypted = cipher.encrypt("hello".toByteArray())
 * val decrypted = cipher.decrypt(encrypted)
 * ```
 *
 * @param key The AES-256 [SecretKey] from Android Keystore.
 *            Defaults to [KeystoreHelper.getOrCreateKey].
 */
class SessionCipher(
    private val key: SecretKey = KeystoreHelper.getOrCreateKey(),
) {

    companion object {
        private const val TRANSFORMATION = "AES/GCM/NoPadding"

        /** GCM authentication tag length in bits */
        private const val GCM_TAG_LENGTH_BITS = 128

        /** GCM IV length in bytes (96 bits as recommended by NIST SP 800-38D) */
        const val GCM_IV_LENGTH_BYTES = 12
    }

    /**
     * Encrypt [plaintext] using AES-256-GCM.
     *
     * A fresh IV is generated by the Android Keystore Cipher for each call,
     * ensuring IV uniqueness without manual random generation.
     *
     * @param plaintext Raw bytes to encrypt.
     * @return [EncryptedPayload] containing the ciphertext (with appended GCM tag) and IV.
     * @throws javax.crypto.IllegalBlockSizeException if plaintext exceeds GCM limits.
     */
    fun encrypt(plaintext: ByteArray): EncryptedPayload {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        // Android Keystore Cipher generates a random IV internally when no IV is specified
        cipher.init(Cipher.ENCRYPT_MODE, key)

        val ciphertext = cipher.doFinal(plaintext)
        val iv = cipher.iv

        return EncryptedPayload(
            ciphertext = ciphertext,
            iv = iv,
        )
    }

    /**
     * Decrypt an [EncryptedPayload] back to plaintext.
     *
     * Verifies the GCM authentication tag during decryption — tampered
     * data will throw [javax.crypto.AEADBadTagException].
     *
     * @param payload The [EncryptedPayload] produced by [encrypt].
     * @return Decrypted plaintext bytes.
     * @throws javax.crypto.AEADBadTagException if the authentication tag is invalid (data tampered).
     * @throws java.security.InvalidKeyException if the key doesn't match.
     */
    fun decrypt(payload: EncryptedPayload): ByteArray {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        val spec = GCMParameterSpec(GCM_TAG_LENGTH_BITS, payload.iv)
        cipher.init(Cipher.DECRYPT_MODE, key, spec)

        return cipher.doFinal(payload.ciphertext)
    }
}
